BEGIN TRANSACTION;
CREATE TABLE answers (
	id INTEGER NOT NULL, 
	text VARCHAR NOT NULL, 
	is_correct BOOLEAN NOT NULL, 
	question_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(question_id) REFERENCES questions (id)
);
INSERT INTO "answers" VALUES(1,'1789',1,1);
INSERT INTO "answers" VALUES(2,'1492',0,1);
INSERT INTO "answers" VALUES(3,'1515',0,1);
INSERT INTO "answers" VALUES(4,'1610',0,1);
INSERT INTO "answers" VALUES(5,'1661',0,1);
INSERT INTO "answers" VALUES(6,'1715',0,1);
INSERT INTO "answers" VALUES(7,'1815',0,1);
INSERT INTO "answers" VALUES(8,'1848',0,1);
INSERT INTO "answers" VALUES(9,'1870',0,1);
INSERT INTO "answers" VALUES(10,'1914',0,1);
INSERT INTO "answers" VALUES(11,'Napoléon Ier',1,2);
INSERT INTO "answers" VALUES(12,'Louis XIV',0,2);
INSERT INTO "answers" VALUES(13,'Charlemagne',0,2);
INSERT INTO "answers" VALUES(14,'Napoléon III',0,2);
INSERT INTO "answers" VALUES(15,'Louis XVI',0,2);
INSERT INTO "answers" VALUES(16,'François Ier',0,2);
INSERT INTO "answers" VALUES(17,'Henri IV',0,2);
INSERT INTO "answers" VALUES(18,'Louis XVIII',0,2);
INSERT INTO "answers" VALUES(19,'Charles X',0,2);
INSERT INTO "answers" VALUES(20,'Philippe Auguste',0,2);
INSERT INTO "answers" VALUES(21,'Le mur de Berlin',1,3);
INSERT INTO "answers" VALUES(22,'Le mur d''Hadrien',0,3);
INSERT INTO "answers" VALUES(23,'La Grande Muraille',0,3);
INSERT INTO "answers" VALUES(24,'Le mur des Lamentations',0,3);
INSERT INTO "answers" VALUES(25,'Le mur de l''Atlantique',0,3);
INSERT INTO "answers" VALUES(26,'Le mur de Varsovie',0,3);
INSERT INTO "answers" VALUES(27,'Le mur de Rome',0,3);
INSERT INTO "answers" VALUES(28,'Le mur de Prague',0,3);
INSERT INTO "answers" VALUES(29,'Le mur de Vienne',0,3);
INSERT INTO "answers" VALUES(30,'Le mur de Moscou',0,3);
INSERT INTO "answers" VALUES(31,'Les Incas',1,4);
INSERT INTO "answers" VALUES(32,'Les Mayas',0,4);
INSERT INTO "answers" VALUES(33,'Les Aztèques',0,4);
INSERT INTO "answers" VALUES(34,'Les Romains',0,4);
INSERT INTO "answers" VALUES(35,'Les Vikings',0,4);
INSERT INTO "answers" VALUES(36,'Les Égyptiens',0,4);
INSERT INTO "answers" VALUES(37,'Les Grecs',0,4);
INSERT INTO "answers" VALUES(38,'Les Celtes',0,4);
INSERT INTO "answers" VALUES(39,'Les Perses',0,4);
INSERT INTO "answers" VALUES(40,'Les Phéniciens',0,4);
INSERT INTO "answers" VALUES(41,'Christophe Colomb',1,5);
INSERT INTO "answers" VALUES(42,'Vasco de Gama',0,5);
INSERT INTO "answers" VALUES(43,'Magellan',0,5);
INSERT INTO "answers" VALUES(44,'James Cook',0,5);
INSERT INTO "answers" VALUES(45,'Marco Polo',0,5);
INSERT INTO "answers" VALUES(46,'Amerigo Vespucci',0,5);
INSERT INTO "answers" VALUES(47,'Hernán Cortés',0,5);
INSERT INTO "answers" VALUES(48,'Francisco Pizarro',0,5);
INSERT INTO "answers" VALUES(49,'Jacques Cartier',0,5);
INSERT INTO "answers" VALUES(50,'Bartolomeu Dias',0,5);
INSERT INTO "answers" VALUES(51,'Louis XIV',1,6);
INSERT INTO "answers" VALUES(52,'Louis XIII',0,6);
INSERT INTO "answers" VALUES(53,'Louis XV',0,6);
INSERT INTO "answers" VALUES(54,'Louis XVI',0,6);
INSERT INTO "answers" VALUES(55,'Henri IV',0,6);
INSERT INTO "answers" VALUES(56,'François Ier',0,6);
INSERT INTO "answers" VALUES(57,'Charles VII',0,6);
INSERT INTO "answers" VALUES(58,'Louis XI',0,6);
INSERT INTO "answers" VALUES(59,'Philippe IV',0,6);
INSERT INTO "answers" VALUES(60,'Charles X',0,6);
INSERT INTO "answers" VALUES(61,'1918',1,7);
INSERT INTO "answers" VALUES(62,'1914',0,7);
INSERT INTO "answers" VALUES(63,'1915',0,7);
INSERT INTO "answers" VALUES(64,'1916',0,7);
INSERT INTO "answers" VALUES(65,'1917',0,7);
INSERT INTO "answers" VALUES(66,'1919',0,7);
INSERT INTO "answers" VALUES(67,'1920',0,7);
INSERT INTO "answers" VALUES(68,'1939',0,7);
INSERT INTO "answers" VALUES(69,'1944',0,7);
INSERT INTO "answers" VALUES(70,'1945',0,7);
INSERT INTO "answers" VALUES(71,'La civilisation grecque',1,8);
INSERT INTO "answers" VALUES(72,'La civilisation romaine',0,8);
INSERT INTO "answers" VALUES(73,'La civilisation égyptienne',0,8);
INSERT INTO "answers" VALUES(74,'La civilisation perse',0,8);
INSERT INTO "answers" VALUES(75,'La civilisation maya',0,8);
INSERT INTO "answers" VALUES(76,'La civilisation inca',0,8);
INSERT INTO "answers" VALUES(77,'La civilisation viking',0,8);
INSERT INTO "answers" VALUES(78,'La civilisation phénicienne',0,8);
INSERT INTO "answers" VALUES(79,'La civilisation gauloise',0,8);
INSERT INTO "answers" VALUES(80,'La civilisation babylonienne',0,8);
INSERT INTO "answers" VALUES(81,'La guerre de Cent Ans',1,9);
INSERT INTO "answers" VALUES(82,'La guerre de Trente Ans',0,9);
INSERT INTO "answers" VALUES(83,'Les guerres napoléoniennes',0,9);
INSERT INTO "answers" VALUES(84,'La guerre de Sept Ans',0,9);
INSERT INTO "answers" VALUES(85,'La guerre de Crimée',0,9);
INSERT INTO "answers" VALUES(86,'La guerre des Gaules',0,9);
INSERT INTO "answers" VALUES(87,'La guerre de Succession d''Espagne',0,9);
INSERT INTO "answers" VALUES(88,'La guerre franco-prussienne',0,9);
INSERT INTO "answers" VALUES(89,'Les croisades',0,9);
INSERT INTO "answers" VALUES(90,'La guerre de 1914-1918',0,9);
INSERT INTO "answers" VALUES(91,'L''Empire romain',1,10);
INSERT INTO "answers" VALUES(92,'L''Empire ottoman',0,10);
INSERT INTO "answers" VALUES(93,'L''Empire byzantin',0,10);
INSERT INTO "answers" VALUES(94,'L''Empire carolingien',0,10);
INSERT INTO "answers" VALUES(95,'L''Empire perse',0,10);
INSERT INTO "answers" VALUES(96,'L''Empire mongol',0,10);
INSERT INTO "answers" VALUES(97,'L''Empire inca',0,10);
INSERT INTO "answers" VALUES(98,'L''Empire aztèque',0,10);
INSERT INTO "answers" VALUES(99,'L''Empire britannique',0,10);
INSERT INTO "answers" VALUES(100,'L''Empire russe',0,10);
INSERT INTO "answers" VALUES(101,'James Cameron',1,11);
INSERT INTO "answers" VALUES(102,'Steven Spielberg',0,11);
INSERT INTO "answers" VALUES(103,'Christopher Nolan',0,11);
INSERT INTO "answers" VALUES(104,'Martin Scorsese',0,11);
INSERT INTO "answers" VALUES(105,'Ridley Scott',0,11);
INSERT INTO "answers" VALUES(106,'George Lucas',0,11);
INSERT INTO "answers" VALUES(107,'Quentin Tarantino',0,11);
INSERT INTO "answers" VALUES(108,'Peter Jackson',0,11);
INSERT INTO "answers" VALUES(109,'David Fincher',0,11);
INSERT INTO "answers" VALUES(110,'Tim Burton',0,11);
INSERT INTO "answers" VALUES(111,'Star Wars',1,12);
INSERT INTO "answers" VALUES(112,'Star Trek',0,12);
INSERT INTO "answers" VALUES(113,'Harry Potter',0,12);
INSERT INTO "answers" VALUES(114,'Le Seigneur des anneaux',0,12);
INSERT INTO "answers" VALUES(115,'Matrix',0,12);
INSERT INTO "answers" VALUES(116,'Alien',0,12);
INSERT INTO "answers" VALUES(117,'Terminator',0,12);
INSERT INTO "answers" VALUES(118,'Dune',0,12);
INSERT INTO "answers" VALUES(119,'Avatar',0,12);
INSERT INTO "answers" VALUES(120,'Jurassic Park',0,12);
INSERT INTO "answers" VALUES(121,'Jurassic Park',1,13);
INSERT INTO "answers" VALUES(122,'Jaws',0,13);
INSERT INTO "answers" VALUES(123,'Avatar',0,13);
INSERT INTO "answers" VALUES(124,'Gladiator',0,13);
INSERT INTO "answers" VALUES(125,'Interstellar',0,13);
INSERT INTO "answers" VALUES(126,'Inception',0,13);
INSERT INTO "answers" VALUES(127,'Rocky',0,13);
INSERT INTO "answers" VALUES(128,'Titanic',0,13);
INSERT INTO "answers" VALUES(129,'Alien',0,13);
INSERT INTO "answers" VALUES(130,'King Kong',0,13);
INSERT INTO "answers" VALUES(131,'Leonardo DiCaprio',1,14);
INSERT INTO "answers" VALUES(132,'Brad Pitt',0,14);
INSERT INTO "answers" VALUES(133,'Tom Cruise',0,14);
INSERT INTO "answers" VALUES(134,'Matt Damon',0,14);
INSERT INTO "answers" VALUES(135,'Johnny Depp',0,14);
INSERT INTO "answers" VALUES(136,'George Clooney',0,14);
INSERT INTO "answers" VALUES(137,'Christian Bale',0,14);
INSERT INTO "answers" VALUES(138,'Hugh Jackman',0,14);
INSERT INTO "answers" VALUES(139,'Keanu Reeves',0,14);
INSERT INTO "answers" VALUES(140,'Will Smith',0,14);
INSERT INTO "answers" VALUES(141,'Pixar',1,15);
INSERT INTO "answers" VALUES(142,'DreamWorks',0,15);
INSERT INTO "answers" VALUES(143,'Studio Ghibli',0,15);
INSERT INTO "answers" VALUES(144,'Warner Bros.',0,15);
INSERT INTO "answers" VALUES(145,'Universal',0,15);
INSERT INTO "answers" VALUES(146,'Paramount',0,15);
INSERT INTO "answers" VALUES(147,'MGM',0,15);
INSERT INTO "answers" VALUES(148,'Lionsgate',0,15);
INSERT INTO "answers" VALUES(149,'A24',0,15);
INSERT INTO "answers" VALUES(150,'Gaumont',0,15);
INSERT INTO "answers" VALUES(151,'Rouge',1,16);
INSERT INTO "answers" VALUES(152,'Bleue',0,16);
INSERT INTO "answers" VALUES(153,'Verte',0,16);
INSERT INTO "answers" VALUES(154,'Jaune',0,16);
INSERT INTO "answers" VALUES(155,'Noire',0,16);
INSERT INTO "answers" VALUES(156,'Blanche',0,16);
INSERT INTO "answers" VALUES(157,'Orange',0,16);
INSERT INTO "answers" VALUES(158,'Violette',0,16);
INSERT INTO "answers" VALUES(159,'Rose',0,16);
INSERT INTO "answers" VALUES(160,'Grise',0,16);
INSERT INTO "answers" VALUES(161,'Quentin Tarantino',1,17);
INSERT INTO "answers" VALUES(162,'David Lynch',0,17);
INSERT INTO "answers" VALUES(163,'James Cameron',0,17);
INSERT INTO "answers" VALUES(164,'Steven Spielberg',0,17);
INSERT INTO "answers" VALUES(165,'Francis Ford Coppola',0,17);
INSERT INTO "answers" VALUES(166,'Martin Scorsese',0,17);
INSERT INTO "answers" VALUES(167,'Stanley Kubrick',0,17);
INSERT INTO "answers" VALUES(168,'Ridley Scott',0,17);
INSERT INTO "answers" VALUES(169,'Guy Ritchie',0,17);
INSERT INTO "answers" VALUES(170,'Wes Anderson',0,17);
INSERT INTO "answers" VALUES(171,'Le Roi Lion',1,18);
INSERT INTO "answers" VALUES(172,'Aladdin',0,18);
INSERT INTO "answers" VALUES(173,'Bambi',0,18);
INSERT INTO "answers" VALUES(174,'Tarzan',0,18);
INSERT INTO "answers" VALUES(175,'Mulan',0,18);
INSERT INTO "answers" VALUES(176,'Hercule',0,18);
INSERT INTO "answers" VALUES(177,'Pocahontas',0,18);
INSERT INTO "answers" VALUES(178,'Dumbo',0,18);
INSERT INTO "answers" VALUES(179,'Ratatouille',0,18);
INSERT INTO "answers" VALUES(180,'Cars',0,18);
INSERT INTO "answers" VALUES(181,'Poudlard',1,19);
INSERT INTO "answers" VALUES(182,'Beauxbâtons',0,19);
INSERT INTO "answers" VALUES(183,'Durmstrang',0,19);
INSERT INTO "answers" VALUES(184,'Narnia',0,19);
INSERT INTO "answers" VALUES(185,'Camelot',0,19);
INSERT INTO "answers" VALUES(186,'Nevermore',0,19);
INSERT INTO "answers" VALUES(187,'Xavier Institute',0,19);
INSERT INTO "answers" VALUES(188,'Gotham Academy',0,19);
INSERT INTO "answers" VALUES(189,'Ilvermorny',0,19);
INSERT INTO "answers" VALUES(190,'Brakebills',0,19);
INSERT INTO "answers" VALUES(191,'Inception',1,20);
INSERT INTO "answers" VALUES(192,'Dunkirk',0,20);
INSERT INTO "answers" VALUES(193,'Tenet',0,20);
INSERT INTO "answers" VALUES(194,'Memento',0,20);
INSERT INTO "answers" VALUES(195,'Interstellar',0,20);
INSERT INTO "answers" VALUES(196,'The Prestige',0,20);
INSERT INTO "answers" VALUES(197,'Insomnia',0,20);
INSERT INTO "answers" VALUES(198,'Oppenheimer',0,20);
INSERT INTO "answers" VALUES(199,'Batman Begins',0,20);
INSERT INTO "answers" VALUES(200,'Following',0,20);
INSERT INTO "answers" VALUES(201,'11',1,21);
INSERT INTO "answers" VALUES(202,'5',0,21);
INSERT INTO "answers" VALUES(203,'6',0,21);
INSERT INTO "answers" VALUES(204,'7',0,21);
INSERT INTO "answers" VALUES(205,'8',0,21);
INSERT INTO "answers" VALUES(206,'9',0,21);
INSERT INTO "answers" VALUES(207,'10',0,21);
INSERT INTO "answers" VALUES(208,'12',0,21);
INSERT INTO "answers" VALUES(209,'13',0,21);
INSERT INTO "answers" VALUES(210,'15',0,21);
INSERT INTO "answers" VALUES(211,'Badminton',1,22);
INSERT INTO "answers" VALUES(212,'Tennis',0,22);
INSERT INTO "answers" VALUES(213,'Squash',0,22);
INSERT INTO "answers" VALUES(214,'Padel',0,22);
INSERT INTO "answers" VALUES(215,'Ping-pong',0,22);
INSERT INTO "answers" VALUES(216,'Baseball',0,22);
INSERT INTO "answers" VALUES(217,'Golf',0,22);
INSERT INTO "answers" VALUES(218,'Hockey',0,22);
INSERT INTO "answers" VALUES(219,'Cricket',0,22);
INSERT INTO "answers" VALUES(220,'Handball',0,22);
INSERT INTO "answers" VALUES(221,'5',1,23);
INSERT INTO "answers" VALUES(222,'1',0,23);
INSERT INTO "answers" VALUES(223,'2',0,23);
INSERT INTO "answers" VALUES(224,'3',0,23);
INSERT INTO "answers" VALUES(225,'4',0,23);
INSERT INTO "answers" VALUES(226,'6',0,23);
INSERT INTO "answers" VALUES(227,'7',0,23);
INSERT INTO "answers" VALUES(228,'8',0,23);
INSERT INTO "answers" VALUES(229,'10',0,23);
INSERT INTO "answers" VALUES(230,'15',0,23);
INSERT INTO "answers" VALUES(231,'France',1,24);
INSERT INTO "answers" VALUES(232,'Croatie',0,24);
INSERT INTO "answers" VALUES(233,'Brésil',0,24);
INSERT INTO "answers" VALUES(234,'Allemagne',0,24);
INSERT INTO "answers" VALUES(235,'Argentine',0,24);
INSERT INTO "answers" VALUES(236,'Espagne',0,24);
INSERT INTO "answers" VALUES(237,'Italie',0,24);
INSERT INTO "answers" VALUES(238,'Portugal',0,24);
INSERT INTO "answers" VALUES(239,'Belgique',0,24);
INSERT INTO "answers" VALUES(240,'Angleterre',0,24);
INSERT INTO "answers" VALUES(241,'Terre battue',1,25);
INSERT INTO "answers" VALUES(242,'Gazon',0,25);
INSERT INTO "answers" VALUES(243,'Dur',0,25);
INSERT INTO "answers" VALUES(244,'Moquette',0,25);
INSERT INTO "answers" VALUES(245,'Parquet',0,25);
INSERT INTO "answers" VALUES(246,'Sable',0,25);
INSERT INTO "answers" VALUES(247,'Glace',0,25);
INSERT INTO "answers" VALUES(248,'Béton',0,25);
INSERT INTO "answers" VALUES(249,'Asphalte',0,25);
INSERT INTO "answers" VALUES(250,'Synthétique',0,25);
INSERT INTO "answers" VALUES(251,'Judo',1,26);
INSERT INTO "answers" VALUES(252,'Boxe',0,26);
INSERT INTO "answers" VALUES(253,'Escrime',0,26);
INSERT INTO "answers" VALUES(254,'Natation',0,26);
INSERT INTO "answers" VALUES(255,'Cyclisme',0,26);
INSERT INTO "answers" VALUES(256,'Aviron',0,26);
INSERT INTO "answers" VALUES(257,'Tennis',0,26);
INSERT INTO "answers" VALUES(258,'Golf',0,26);
INSERT INTO "answers" VALUES(259,'Handball',0,26);
INSERT INTO "answers" VALUES(260,'Volley-ball',0,26);
INSERT INTO "answers" VALUES(261,'5',1,27);
INSERT INTO "answers" VALUES(262,'4',0,27);
INSERT INTO "answers" VALUES(263,'6',0,27);
INSERT INTO "answers" VALUES(264,'7',0,27);
INSERT INTO "answers" VALUES(265,'8',0,27);
INSERT INTO "answers" VALUES(266,'9',0,27);
INSERT INTO "answers" VALUES(267,'10',0,27);
INSERT INTO "answers" VALUES(268,'11',0,27);
INSERT INTO "answers" VALUES(269,'12',0,27);
INSERT INTO "answers" VALUES(270,'15',0,27);
INSERT INTO "answers" VALUES(271,'Cyclisme',1,28);
INSERT INTO "answers" VALUES(272,'Athlétisme',0,28);
INSERT INTO "answers" VALUES(273,'Rallye',0,28);
INSERT INTO "answers" VALUES(274,'MotoGP',0,28);
INSERT INTO "answers" VALUES(275,'Triathlon',0,28);
INSERT INTO "answers" VALUES(276,'Ski',0,28);
INSERT INTO "answers" VALUES(277,'Natation',0,28);
INSERT INTO "answers" VALUES(278,'Aviron',0,28);
INSERT INTO "answers" VALUES(279,'Football',0,28);
INSERT INTO "answers" VALUES(280,'Tennis',0,28);
INSERT INTO "answers" VALUES(281,'42,195 km',1,29);
INSERT INTO "answers" VALUES(282,'10 km',0,29);
INSERT INTO "answers" VALUES(283,'20 km',0,29);
INSERT INTO "answers" VALUES(284,'21,1 km',0,29);
INSERT INTO "answers" VALUES(285,'30 km',0,29);
INSERT INTO "answers" VALUES(286,'35 km',0,29);
INSERT INTO "answers" VALUES(287,'40 km',0,29);
INSERT INTO "answers" VALUES(288,'45 km',0,29);
INSERT INTO "answers" VALUES(289,'50 km',0,29);
INSERT INTO "answers" VALUES(290,'100 km',0,29);
INSERT INTO "answers" VALUES(291,'Tennis',1,30);
INSERT INTO "answers" VALUES(292,'Golf',0,30);
INSERT INTO "answers" VALUES(293,'Cricket',0,30);
INSERT INTO "answers" VALUES(294,'Rugby',0,30);
INSERT INTO "answers" VALUES(295,'Football',0,30);
INSERT INTO "answers" VALUES(296,'Badminton',0,30);
INSERT INTO "answers" VALUES(297,'Squash',0,30);
INSERT INTO "answers" VALUES(298,'Hockey',0,30);
INSERT INTO "answers" VALUES(299,'Polo',0,30);
INSERT INTO "answers" VALUES(300,'Baseball',0,30);
CREATE TABLE categories (
	id INTEGER NOT NULL, 
	name VARCHAR NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (name)
);
INSERT INTO "categories" VALUES(1,'Histoire');
INSERT INTO "categories" VALUES(2,'Cinéma');
INSERT INTO "categories" VALUES(3,'Sport');
CREATE TABLE questions (
	id INTEGER NOT NULL, 
	text VARCHAR NOT NULL, 
	category_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(category_id) REFERENCES categories (id)
);
INSERT INTO "questions" VALUES(1,'En quelle année a débuté la Révolution française ?',1);
INSERT INTO "questions" VALUES(2,'Qui fut le premier empereur des Français ?',1);
INSERT INTO "questions" VALUES(3,'Quel mur est tombé en 1989 ?',1);
INSERT INTO "questions" VALUES(4,'Quel peuple a construit le Machu Picchu ?',1);
INSERT INTO "questions" VALUES(5,'Qui a découvert l''Amérique en 1492 selon le récit historique européen traditionnel ?',1);
INSERT INTO "questions" VALUES(6,'Quel roi français était surnommé le Roi-Soleil ?',1);
INSERT INTO "questions" VALUES(7,'La Première Guerre mondiale s''est terminée en quelle année ?',1);
INSERT INTO "questions" VALUES(8,'Quelle civilisation antique avait Athènes pour grande cité ?',1);
INSERT INTO "questions" VALUES(9,'Jeanne d''Arc est associée à quelle guerre ?',1);
INSERT INTO "questions" VALUES(10,'Quel empire avait Rome pour capitale ?',1);
INSERT INTO "questions" VALUES(11,'Qui a réalisé Titanic ?',2);
INSERT INTO "questions" VALUES(12,'Dans quelle saga trouve-t-on Dark Vador ?',2);
INSERT INTO "questions" VALUES(13,'Quel film met en scène un parc rempli de dinosaures ?',2);
INSERT INTO "questions" VALUES(14,'Quel acteur joue Jack dans Titanic ?',2);
INSERT INTO "questions" VALUES(15,'Quel studio est à l''origine de Toy Story ?',2);
INSERT INTO "questions" VALUES(16,'Dans Matrix, quelle couleur a la pilule choisie par Neo ?',2);
INSERT INTO "questions" VALUES(17,'Quel réalisateur a signé Pulp Fiction ?',2);
INSERT INTO "questions" VALUES(18,'Quel film d''animation met en scène Simba ?',2);
INSERT INTO "questions" VALUES(19,'Dans Harry Potter, quelle école fréquente le héros ?',2);
INSERT INTO "questions" VALUES(20,'Quel film de Christopher Nolan parle de rêves imbriqués ?',2);
INSERT INTO "questions" VALUES(21,'Combien de joueurs une équipe de football aligne-t-elle sur le terrain au coup d''envoi ?',3);
INSERT INTO "questions" VALUES(22,'Dans quel sport utilise-t-on un volant ?',3);
INSERT INTO "questions" VALUES(23,'Combien de points vaut un essai au rugby à XV ?',3);
INSERT INTO "questions" VALUES(24,'Quel pays a remporté la Coupe du monde de football 2018 ?',3);
INSERT INTO "questions" VALUES(25,'Sur quelle surface se joue traditionnellement Roland-Garros ?',3);
INSERT INTO "questions" VALUES(26,'Quel sport pratique-t-on sur un tatami avec des projections ?',3);
INSERT INTO "questions" VALUES(27,'Combien de joueurs sont sur le terrain par équipe au basket-ball ?',3);
INSERT INTO "questions" VALUES(28,'Dans quel sport trouve-t-on le Tour de France ?',3);
INSERT INTO "questions" VALUES(29,'Quelle distance mesure approximativement un marathon ?',3);
INSERT INTO "questions" VALUES(30,'Quel sport est associé à Wimbledon ?',3);
CREATE INDEX ix_categories_id ON categories (id);
CREATE INDEX ix_questions_id ON questions (id);
CREATE INDEX ix_answers_id ON answers (id);
COMMIT;